# Generated by Django 4.2.16 on 2024-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='date_published',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
    ]
